name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy to Docker registry (CI)
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          repository: haroongit/myproductpix-web
          tag_with_ref: true
          push: true
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - uses: actions/checkout@v2
    - name: SSH and deploy node app (CD)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker rm -f myproductpix-web
          docker rmi -f haroongit/myproductpix-web:main
          docker pull haroongit/myproductpix-web:main
          docker run -d --name myproductpix-web --net="host" haroongit/myproductpix-web:main
          exit
